#
# ~/.bashrc
#

# Called by bash when used as an interactive shell

[[ $- != *i* ]] && return

# Automatically adjust the values of LINES and COLUMNS after each command
shopt -s checkwinsize

# Enable bash autocompletion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Enable extra features if we're in a VTE terminal
[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

# Locate bash dotfiles
export DOTFILES="/home/ekalderon/.dotfiles"
FILES=`find $DOTFILES/bash/ -type f | sort`

# Load all files found
for FILE in $FILES; do
    . $FILE
done

