#!/usr/bin/env bash

set -euo pipefail

STOW_DELETE='stow --verbose --delete'

echo 'Uninstalling dotfiles...'
$STOW_DELETE cointop bash fzf git ncmpcpp neovim tmux top

case "$OSTYPE" in
  linux*)
    $STOW_DELETE gnupg-linux mpd-linux
    [ -d ~/.config/mpd ] && rm -r ~/.config/mpd
    [ -d ~/.local/share/mpd ] && rm -r ~/.local/share/mpd
    ;;
  darwin*)
    $STOW_DELETE gnupg-macos iterm2 mpd-macos
    [ -d ~/.mpd ] && rm -r ~/.mpd
    ;;
  *) ;;
esac

if [ -d ~/.bashrc.d ]; then
  echo 'Deleting any broken symlinks, if any...'
  find ~/.bashrc.d -xtype l -delete -print
  rmdir --ignore-fail-on-non-empty ~/.bashrc.d || true
fi
