#!/usr/bin/env bash

#
# lib/backup
#
# Backing up files, managing symlinks, and restoring from earlier backups
#

backup_and_copy() {
  local src="$1"
  local dest="$2"

  echo -n "copying ${dest}... "

  # If file/folder exists, back it up
  if [[ -e ${dest} ]]; then
    cp -prf "${dest}" "${PACKAGE_BACKUPS}/"
  fi

  # Copy file to destination
  sudo cp -rpf "${src}" "${dest}" || { error && return 1; }
  ok

  return 0
}

backup_and_link() {
  local src="$1"
  local dest="$2"

  echo -n "linking ${dest}... "

  # If file/folder exists, back it up
  if [[ -f ${dest} ]] || [[ -L ${dest} ]]; then
    mv "${dest}" "${PACKAGE_BACKUPS}/"
  elif [[ -d ${dest} ]]; then
    cp -rpf "${dest}" "${PACKAGE_BACKUPS}/"
  fi

  # Create new symlink
  ln -s "${src}" "${dest}" || { error && return 1; }
  ok

  return 0
}

restore() {
  local name dest date src
  name="$1"
  dest="$2"
  date="$3"

  echo -n "restoring ${name}... "

  if [[ -n ${date} ]]; then
    src="${HOME}/.dotfiles_old/${date}/${name}"
  else
    # Select the oldest backup directory that contains this file
    src=$(find "${HOME}/.dotfiles_old/" -name "${name}" | head -1)
  fi

  # Copy the backed up file
  cp -rpf "${src}" "${dest}" &> /dev/null || { error && return 1; }
  ok

  return 0
}
