#!/usr/bin/env bash

#
# lib/backup
#
# Backing up files, managing symlinks, and restoring from earlier backups
#

backup_and_copy() {
  local src="$1"
  local dest="$2"

  running "copying ${dest}..."

  # If file/folder exists, back it up
  if [[ -e ${dest} ]]; then
    cp -prf "${dest}" "${PACKAGE_BACKUPS}/"
  fi

  # Copy file to destination
  if sudo cp -rpf "${src}" "${dest}"; then
    ok
    return 0
  else
    error
    return 1
  fi
}

backup_and_link() {
  local src="$1"
  local dest="$2"

  running "linking ${dest}..."

  # If file/folder exists, back it up
  if [[ -f ${dest} ]] || [[ -L ${dest} ]]; then
    mv "${dest}" "${PACKAGE_BACKUPS}/"
  elif [[ -d ${dest} ]]; then
    cp -rpf "${dest}" "${PACKAGE_BACKUPS}/"
  fi

  # Create new symlink
  if ln -s "${src}" "${dest}"; then
    ok
    return 0
  else
    error
    return 1
  fi
}

restore() {
  local name dest date src
  name="$1"
  dest="$2"
  date="$3"

  running "restoring ${name}..."

  if [[ -n ${date} ]]; then
    src="${HOME}/.dotfiles_old/${date}/${name}"
  else
    # Select the oldest backup directory that contains this file
    src="$(find "${HOME}/.dotfiles_old/" -name "${name}" | head -1)"
  fi

  # Copy the backed up file
  if cp -rpf "${src}" "${dest}" &> /dev/null; then
    ok
    return 0
  else
    error
    return 1
  fi
}
