#!/bin/sh

#
# lib/output
#
# Useful logging output functions
#

function ok() {
    echo -e "[ok] "$1
}

function warning() {
    echo -e "[warning] "$1
}

function error() {
    echo -e "[error] "$1
}

function success() {
    echo -e "[success] "$1
}

function failure() {
    echo -e "[failure] "$1
}
