#!/usr/bin/env bash

#
# lib/output
#
# Useful output functions for logging
#

readonly COLOR_BLACK="$(tput setaf 0)"
readonly COLOR_RED="$(tput setaf 1)"
readonly COLOR_GREEN="$(tput setaf 2)"
readonly COLOR_YELLOW="$(tput setaf 3)"
readonly COLOR_LIME_YELLOW="$(tput setaf 190)"
readonly COLOR_POWDER_BLUE="$(tput setaf 153)"
readonly COLOR_BLUE="$(tput setaf 4)"
readonly COLOR_MAGENTA="$(tput setaf 5)"
readonly COLOR_CYAN="$(tput setaf 6)"
readonly COLOR_WHITE="$(tput setaf 7)"

readonly STYLE_RESET="$(tput sgr0)"
readonly STYLE_BOLD="$(tput bold)"
readonly STYLE_BLINK="$(tput blink)"
readonly STYLE_REVERSE="$(tput smso)"
readonly STYLE_UNDERLINE="$(tput smul)"

readonly CURSOR_PREV_LINE="$(tput cuu1 && tput cr)"

debug() {
  if [[ ${VERBOSE} == 1 ]]; then
    echo -e "${STYLE_BOLD}VERBOSE:${STYLE_RESET} ${1:-}"
  fi
}

header() {
  local text="$1"
  echo -e "${COLOR_BLUE}${STYLE_BOLD}:: ${COLOR_WHITE}${text}${STYLE_RESET}"
}

running() {
  local text="$1"
  echo -e "       ${text}"
}

ok() {
  local text="${1:-}"
  if [ -n "${text}" ]; then
    echo -e "${STYLE_BOLD}${COLOR_GREEN}  [ok]${STYLE_RESET} ${text}"
  else
    echo -e "${CURSOR_PREV_LINE}${STYLE_BOLD}${COLOR_GREEN}  [ok]${STYLE_RESET}"
  fi
}

warning() {
  local text="${1:-}"
  if [ -n "${text}" ]; then
    echo -e "${STYLE_BOLD}${COLOR_YELLOW}[warn]${STYLE_RESET} ${text}"
  else
    echo -e "${CURSOR_PREV_LINE}${STYLE_BOLD}${COLOR_YELLOW}[warn]${STYLE_RESET}"
  fi
}

error() {
  local text="${1:-}"
  if [ -n "${text}" ]; then
    echo -e "${STYLE_BOLD}${COLOR_RED} [err]${STYLE_RESET} ${text}"
  else
    echo -e "${CURSOR_PREV_LINE}${STYLE_BOLD}${COLOR_RED} [err]${STYLE_RESET}"
  fi
}

success() {
  local text="${1:-}"
  if [ -n "${text}" ]; then
    echo -e "${STYLE_BOLD}${COLOR_GREEN}   [✓]${STYLE_RESET} ${text}"
  else
    echo -e "${CURSOR_PREV_LINE}${STYLE_BOLD}${COLOR_GREEN}   [✓]${STYLE_RESET}"
  fi
}

failure() {
  local text="${1:-}"
  if [ -n "${text}" ]; then
    echo -e "${STYLE_BOLD}${COLOR_RED}   [✗]${STYLE_RESET} ${text}"
  else
    echo -e "${CURSOR_PREV_LINE}${STYLE_BOLD}${COLOR_RED}   [✗]${STYLE_RESET}"
  fi
}
