#!/usr/bin/env bash

#
# lib/package
#
# Functions for handling dotfiles packages.
#

readonly BACKUP_DIR="${HOME}/.dotfiles_old/$(date +'%Y.%m.%d.%H.%M.%S')"
readonly DATABASE="${DOTFILES}/packages/installed"
readonly PACKAGES="$(find "${DOTFILES}/packages/" -name 'package' -type f | sort)"

packages_list() {
  for package in ${PACKAGES}; do
    _load_package "${package}"
    printf '  %-9s %s\n' "${PACKAGE_NAME}" "${DESCRIPTION}"
  done
}

packages_install() {
  touch "${DATABASE}"

  for package in ${PACKAGES}; do
    _load_package "${package}"

    # Check if package supports this platform
    debug "Package '${PACKAGE_NAME}' supports platforms '${PLATFORMS}'"
    if ! platform_check_string "${PLATFORMS}"; then
      header "Package '${PACKAGE_NAME}' does not support '${PLATFORM_NAME}'. Skipping..."
      continue
    fi

    # Create a package-specific backup directory and install the package
    header "${INSTALL_MSG}"
    mkdir -p "${PACKAGE_BACKUPS}"
    _install || continue

    # If package name isn't present in the list of installed packages, add it
    if ! grep -Ex --quiet "${PACKAGE_NAME}" "${DATABASE}"; then
      echo "${PACKAGE_NAME}" >> "${DATABASE}"
    fi
  done
}

packages_uninstall() {
  touch "${DATABASE}"

  for package in ${PACKAGES}; do
    _load_package "${package}"

    # If package is not currently installed, skip it
    if ! grep -Ex --quiet "${PACKAGE_NAME}" "${DATABASE}"; then
      header "Package '${PACKAGE_NAME}' not installed. Skipping..."
      continue
    fi

    # Uninstall the package
    header "${UNINSTALL_MSG}"
    _uninstall

    # Remove it from the list of installed packages
    grep -Exv "${PACKAGE_NAME}" "${DATABASE}" > "${DATABASE}.tmp"
    mv "${DATABASE}.tmp" "${DATABASE}"
  done
}

packages_pre_update() {
  header 'Triggering pre-updates...'

  for package in ${PACKAGES}; do
    _load_package "${package}"

    # If package is not currently installed, skip it
    if ! grep -Ex --quiet "${PACKAGE_NAME}" "${DATABASE}"; then
      header "Package '${PACKAGE_NAME}' not installed. Skipping..."
      continue
    fi

    _pre_update
  done
}

packages_post_update() {
  header 'Triggering post-updates...'

  for package in ${PACKAGES}; do
    _load_package "${package}"

    # If package is not currently installed, skip it
    if ! grep -Ex --quiet "${PACKAGE_NAME}" "${DATABASE}"; then
      header "Package '${PACKAGE_NAME}' not installed. Skipping..."
      continue
    fi

    _post_update
  done
}

packages_reload() {
  touch "${DATABASE}"

  for package in ${PACKAGES}; do
    _load_package "${package}"

    # If package is currently installed, reload it
    if grep -Ex --quiet "${PACKAGE_NAME}" "${DATABASE}"; then
      debug "Reloading '${PACKAGE_NAME}'..."
      _reload
    fi
  done
}

_load_package() {
  local package="$1"

  # Unset all package-defined functions, just in case
  for fn in install uninstall pre_update post_update reload; do
    eval "${fn}() { return; }"
  done

  # Set default values for available variables
  PACKAGE_FILES="$(dirname "${package}")/files"
  PACKAGE_NAME="$(basename "$(dirname "${package}")")"
  PACKAGE_BACKUPS="${BACKUP_DIR}/${PACKAGE_NAME}"
  DESCRIPTION="No description available."
  INSTALL_MSG="Installing \"${PACKAGE_NAME}\" package..."
  UNINSTALL_MSG="Uninstalling \"${PACKAGE_NAME}\" package..."
  PLATFORMS='ANY'

  # Load the contents of the package
  source "${package}"

  # Wrap each function such that package-specific contstants are read-only
  for fn in install uninstall pre_update post_update reload; do
    eval "_${fn}() {
      local -r PACKAGE_BACKUPS=\"${PACKAGE_BACKUPS}\"
      local -r PACKAGE_NAME=\"${PACKAGE_NAME}\"
      local -r PACKAGE_FILES=\"${PACKAGE_FILES}\"
      ${fn}
    }"
  done
}
