#!/bin/bash

#
# lib/system
#
# Functions for executing external processes and checking for errors.
#

execute() {
  local args="$@"

  if [[ ${VERBOSE} == 1 ]]; then
    echo
    debug "${args}"
    ${args}
    return $?
  fi

  ${args} &> /dev/null
  local err="$?"

  if [[ ${err} != 0 ]]; then
    error
  else
    ok
  fi

  return ${err}
}
