#!/bin/bash

#
# lib/system
#
# Functions for executing external processes and checking for errors.
#

execute() {
  local args="$@"

  if [[ ${VERBOSE} -eq 1 ]]; then
    echo
    echo "${STYLE_BOLD}VERBOSE:${STYLE_RESET} ${args}"
    
    ${args}
    return $?
  fi

  ${args} &> /dev/null
  local err="$?"

  if [[ ${err} != 0 ]]; then
    error
  else
    ok
  fi

  return ${err}
}
